### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by mawippel** [mawippel/escape-filas-frontend#1]
- [x] Create LineReporter Modal when user clicks the "Report Line" button;
- [x] Send lat/lgn to the backend when the user's location change;
- [ ] Filter the result of the Search input by location proximity;
