### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mawippel** [mawippel/escape-filas-frontend#2]
- [x] Efetuar o push ao invés de navigate (this.props.navigation.push);
- [x] Tentar conectar um Stateless Component ao Redux;
- [x] Adicionar Quantidade no reportLine();
- [x] ScrollView do report das filas;
- [x] Campo de pesquisa das filas;
- [x] Procurar ícone para a tela de Filas;
- [x] Refatorar tela de Registro
- [x] Focar no próximo campo no onSubmitEditing do Login/Signup;
- [x] Resize do icone de Filas; Adiciona-lo no Projeto;
- [x] Upgrade para o expo 33;
- [x] Converter todos os StyleSheets para StyledComponents;
- [x] Adicionar Icone da quantidade de fila na Lista de Filas, baseado no nivel da fila;
- [x] Adicionar botao de QR Code no canto inferior direito da tela;
- [x] Adicionar funcionalidade de leitura de QR Code;
- [x] Alterar o endpoint fetchLines() para buscar o `{ "query": "{ placeLines { placeId quantity placeName } }" }`
