### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mawippel** [mawippel/escape-filas-frontend#4]
- [x] Validar o funcionamento da feature do QRCode ( `{"placeId":"awefawefawefawe","name":"Giassi da Massa"}` )
- [x] Apresentar o placeName ao scanear um QRCode
- [x] Utilizar o endpoint de filas por proximidade na tela de filas
